name: Python lint
description: Check python coding style

inputs:
  python-version:
    description: Python version to lint code
    required: true
  exclude-paths:
    description: List of files or directories to skip
    required: false

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8
    - name: Lint with flake8
      shell: bash
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Analysing the code with pylint
      shell: bash
      run: |
        pylint --ignore-paths=$(pwd)/${{ join(inputs.exclude-paths, ',$(pwd)/') }} $(pwd)
